# Autogenerated wrapper script for patch_jll for powerpc64le-linux-gnu
export patch

JLLWrappers.@generate_wrapper_header("patch")
JLLWrappers.@declare_executable_product(patch)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        patch,
        "bin/patch",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
